### ISSUE TITLE
Monokai-STE theme for Visual Studio

### ISSUE THREAD

**Issue by TrevorPauley** [volosovich/Monokai-ST3-theme-for-vscode#1]
After switching from Sublime Text 3 to VSCode, I was happy to see that there was a theme extension available. But I recently switched from VSCode to Visual Studio 2017, and I was wondering if you have created a Theme for Visual Studio as well. 

Thanks!

**Comment by volosovich** [comment]
Hi, I doesn't work with big visual studio. So, if you want,  you can clone repo and do it by yourself.
