### ISSUE TITLE
Semantic Highlight

### ISSUE THREAD

**Issue by ItamarShDev** [volosovich/Monokai-ST3-theme-for-vscode#11]
Is there any option to add Semantic Highlight for js in vscode?

**Comment by ElectricRCAircraftGuy** [comment]
I don't know what you're asking, but if you'd like to customize your colors see my tutorial here on how to do so by using the "Scope inspector" tool: https://github.com/volosovich/Monokai-ST3-theme-for-vscode/issues/14.

**Comment by ElectricRCAircraftGuy** [comment]
If you'd like to customize your colors see my tutorial here on how to do so by using the "Scope inspector" tool in VSCode: https://github.com/volosovich/Monokai-ST3-theme-for-vscode/issues/14.
